version: "3.8"

services:

  frontend:
    build: ./FRONTEND
    image: frontend-image
    container_name: frontend-container
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./BACKEND
    image: backend-image
    container_name: backend-container
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:postgresql://database:5432/plan_pro_database
    depends_on:
      - database

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - database

  database:
    image: postgres:alpine
    container_name: database-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plan_pro_database